from sqlalchemy import Boolean, Column, ForeignKey, Integer, String
from sqlalchemy.orm import relationship

#from . import Base
import database
Base= database.Base


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True)
    first_name = Column(String, index=True)
    last_name = Column(String, index=True)
    signup_phone = Column(String, index=True)
    signup_country = Column(String, index=True)
    signup_province_state = Column(String, index=True)
    signup_city = Column(String, index=True)
    signup_house_street = Column(String, index=True)
    signup_zip_code = Column(String, index=True)
    signup_license_no = Column(String, index=True)
    signup_license_exp_date = Column(String, index=True)
    signup_agent_refferor = Column(String, index=True)
    hashed_password = Column(String)
    is_active = Column(Boolean, default=True)

    items = relationship("Item", back_populates="owner")
    houses = relationship("House", back_populates="owner_h")
    condos = relationship("Condo", back_populates="owner_s")


class Item(Base):
    __tablename__ = "items"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, index=True)
    description = Column(String, index=True)
    car_info_json = Column(String, index=True)
    car_brand = Column(String, index=True)
    car_series_name = Column(String, index=True)
    car_year = Column(String, index=True)
    car_make = Column(String, index=True)
    car_fair_market_value = Column(String, index=True)
    car_sum_assured = Column(String, index=True)
    car_own_damage_theft = Column(String, index=True)
    car_excess_bodily_injury = Column(String, index=True)
    car_excess_bodily_injury = Column(String, index=True)
    car_property_damage = Column(String, index=True)
    car_auto_personal_accident = Column(String, index=True)
    car_medical_reinbursment = Column(String, index=True)
    car_total_amount_due = Column(String, index=True)
    car_sum_assured_calculator = Column(String, index=True)
    car_excess_bodily_injury_manual = Column(String, index=True)
    car_your_rate = Column(String, index=True)
    car_cptl = Column(String, index=True)
    car_premium = Column(String, index=True)
    car_doc_stamps = Column(String, index=True)
    car_vat = Column(String, index=True)
    car_local_government_tax = Column(String, index=True)
    car_cptl_val = Column(String, index=True)
    car_other_charges = Column(String, index=True)
    car_insurance_info_firstname = Column(String, index=True)
    car_insurance_info_lastname = Column(String, index=True)
    car_insurance_info_contact = Column(String, index=True)
    car_insurance_info_email = Column(String, index=True)

    owner_id = Column(Integer, ForeignKey("users.id"))

    owner = relationship("User", back_populates="items")

class House(Base):
    __tablename__ = "house"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, index=True)
    description = Column(String, index=True)
    house_info_json = Column(String, index=True)
    doc_stamps = Column(String, index=True)
    fire_service_stamps = Column(String, index=True)
    house_external_walls_entirely_concrete = Column(String, index=True)
    house_located_inside_village_subdivision = Column(String, index=True)
    house_no_boundaries = Column(String, index=True)
    house_no_building_amount = Column(String, index=True)
    house_no_city = Column(String, index=True)
    house_no_construction = Column(String, index=True)
    house_no_construction_other = Column(String, index=True)
    house_no_contents_amount = Column(String, index=True)
    house_no_country = Column(String, index=True)
    house_no_firefighting_mitigating_measure_equipment = Column(String, index=True)
    house_no_house_street = Column(String, index=True)
    house_no_items_to_insure = Column(String, index=True)
    house_no_number_of_stories = Column(String, index=True)
    house_no_perils_covered_aon = Column(String, index=True)
    house_no_perils_covered_auto_personal_accident = Column(String, index=True)
    house_no_perils_covered_own_damage_theft = Column(String, index=True)
    house_no_perils_excess_bodily_injury = Column(String, index=True)
    house_no_perils_medical_reimbursement = Column(String, index=True)
    house_no_perils_property_damage = Column(String, index=True)
    house_no_province = Column(String, index=True)
    house_no_province_state = Column(String, index=True)
    house_no_residential_home_package_options = Column(String, index=True)
    house_no_zip_code = Column(String, index=True)
    house_used_entirely_as_residence = Column(String, index=True)
    house_yes_city = Column(String, index=True)
    house_yes_country = Column(String, index=True)
    house_yes_email = Column(String, index=True)
    house_yes_house_street = Column(String, index=True)
    house_yes_last_name = Column(String, index=True)
    house_yes_name = Column(String, index=True)
    house_yes_phone = Column(String, index=True)
    house_yes_province_state = Column(String, index=True)
    house_yes_zip_code = Column(String, index=True)
    vat = Column(String, index=True)
    local_govt_tax = Column(String, index=True)
    premium = Column(String, index=True)
    sum_assured = Column(String, index=True)
    total_amount_due = Column(String, index=True)
    owner_id = Column(Integer, ForeignKey("users.id"))

    owner_h = relationship("User", back_populates="houses")

class Condo(Base):
    __tablename__ = "condo"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, index=True)
    description = Column(String, index=True)
    condo_info_json = Column(String, index=True)
    condo_external_walls_entirely_concrete = Column(String, index=True)
    condo_no_boundaries = Column(String, index=True)
    condo_no_building_amount = Column(String, index=True)
    condo_no_city = Column(String, index=True)
    condo_no_construction = Column(String, index=True)
    condo_no_contents_amount = Column(String, index=True)
    condo_no_country = Column(String, index=True)
    condo_no_firefighting_mitigating_measure_equipment = Column(String, index=True)
    condo_no_items_to_insure = Column(String, index=True)
    condo_no_number_of_stories = Column(String, index=True)
    condo_no_perils_covered_aon = Column(String, index=True)
    condo_no_perils_covered_auto_personal_accident = Column(String, index=True)
    condo_no_perils_covered_own_damage_theft = Column(String, index=True)
    condo_no_perils_excess_bodily_injury = Column(String, index=True)
    condo_no_perils_medical_reimbursement = Column(String, index=True)
    condo_no_perils_property_damage = Column(String, index=True)
    condo_no_province_state = Column(String, index=True)
    condo_no_roofing = Column(String, index=True)
    condo_no_roofing_others = Column(String, index=True)
    condo_no_zip_code = Column(String, index=True)
    condo_yes_city = Column(String, index=True)
    condo_yes_condo_street = Column(String, index=True)
    condo_yes_country = Column(String, index=True)
    condo_yes_email = Column(String, index=True)
    condo_yes_name = Column(String, index=True)
    condo_yes_no_occupancy = Column(String, index=True)
    condo_yes_phone = Column(String, index=True)
    condo_yes_province_state = Column(String, index=True)
    condo_yes_residential_home_package_option = Column(String, index=True)
    condo_yes_zip_code = Column(String, index=True)
    doc_stamps = Column(String, index=True)
    fire_service_stamps = Column(String, index=True)
    vat = Column(String, index=True)
    local_govt_tax = Column(String, index=True)
    premium = Column(String, index=True)
    sum_assured = Column(String, index=True)
    total_amount_due = Column(String, index=True)
    owner_id = Column(Integer, ForeignKey("users.id"))

    owner_s = relationship("User", back_populates="condos")